### ISSUE TITLE
Can't find gvr audio renderer in wwise with gvr audio sdk installed

### ISSUE THREAD

**Issue by ROM72** [googlevr/gvr-audio-wwise-sdk#1]
I’m following the google vr user guide installation but it’s not very precise. 

Even if I find Ambisonic 3-3 as mentioned in the user guide at instruction n°2
I’m not able to « Add GVR Audio Renderer as an effect to the Ambisonic bus. » I only find wwise default plugins.  The user guide says to put copy the files into the wwise installation folder, so I put it there : « Applications/Audiokinetic/Wwise 2016/Wwise »
I think I’m missing something but I don’t know what. Did anyone experienced this issue ?

my wwise version is 2016.2.1 5995 
my unity version is 5.6.0.b9
I running these softs on mac osx 10.11.6

thanks,

**Comment by anokta** [comment]
Hi,

For working with Wwise Authoring on Mac, you also need to update the application via command line for the plugins to be registered properly.

Please see the **Installation on Mac OS X** section in the following link for details:
https://www.audiokinetic.com/library/edge/?source=SDK&id=plugin__install.html

Let me know if we can provide any further help on that (incl. in terms of documentation etc.).

Cheers

**Comment by ROM72** [comment]
Thanks a lot ! I'm following the procedure but I get an error when I write this command :

CX_ROOT=/Applications/Audiokinetic/WWISE_VERSION/Wwise.app/Contents/SharedSupport/Wwise2016 WINEPREFIX=/Applications/Audiokinetic/WWISEVERSION/Wwise.app/Contents/SharedSupport/Wwise2016/support/wwise ./bin/wineprefixcreate --snapshot."

I get this  error on my terminal : 
"wineprefixcreate:error: unknown '--snapshot.' option
wineprefixcreate:error: try 'wineprefixcreate --help' for more information"

when I type "wineprefixcreate --help" in the terminal I also get "command not found"

Although I installed wine and winetricks, the command wineprefixcreate is still unknown

do you know where this problem comes from  ?

**Comment by ROM72** [comment]
okay shame on me, I think the last dot just after the "snapshot" command got me.
It's working now !
