### ISSUE TITLE
Voice Starvation in Unity due to GVR Audio Renderer

### ISSUE THREAD

**Issue by EgilSandfeld** [googlevr/gvr-audio-wwise-sdk#2]
I have a setup, where audio gets spatialized in Wwise using the GVR Audio Renderer, and then sent to Unity. It works fine, but it comes with Voice Starvation galore. Even if I just set it to play and spatialize 1 sound only.

Some discoveries:

- Unchecking "Inclusion" for the GVR Audio Renderer effect does stop the Voice starvation, but as you might have guessed, also stops the spatialization.

- Changing to Ambisonics 1-1, 2-2 or 3-3 on the spatializing bus does not change anything.

- Plugin CPU is around 6% with 1 instance on Windows PC, so nothing troubling although native Wwise effects are usually <1%

- The voice starvation comes exactly when the sound is started

- Once one sound is playing, voice starvation doesn't come again - it's only appearing when the first sound is being spatialized after silence in that spatializing bus.

Any ideas on how to solve this or mitigate the voice starvation?

![capture](https://cloud.githubusercontent.com/assets/5029330/24455602/8042a104-1490-11e7-8b3a-b7077903aa18.PNG)

**Comment by EgilSandfeld** [comment]
Asking Wwise Wwizards on FB, one user replied:

Possibly, the initialization of the Google VR plug-in may be doing some I/O or calling some external function, or blocking on some Lock. This would not be recommended for plug-ins to do such processing while inside the execution thread.

You should notify Google about this.

^^ I don't know if this is relevant?

**Comment by ak-alessard** [comment]
Additional information:
Voice starvation here means the Wwise Audio Execution thread could not deliver an audio buffer on Time due to some processing taking too much time.
The CPU % usage is time based, not actual processing time. So either the plug-in is doing some intense processing at this time or is waiting on some external job completion before returning from the initialization.

**Comment by EgilSandfeld** [comment]
Additional info:

Running on Nexus 6P (root), GVR Audio Renderer CPU usage might go as high as 75%, making audio stutter a lot. Tried it with Galaxy S7 as well, where CPU usage is not as high, although considerably higher than on PC.

**Comment by anokta** [comment]
Hi all,

Thanks for reporting this! The voice starvation issues during initialization should be resolved now by the v0.3.0 update (7c43972). 

Cheers

**Comment by EgilSandfeld** [comment]
That is wonderful! Thanks so much for fixing it. Will report if it doesn't work ;)
