### ISSUE TITLE
Wwisegvraudio room dont works 

### ISSUE THREAD

**Issue by anonimorph** [googlevr/gvr-audio-wwise-sdk#3]
Hello everyone!

I use wwise middleware to implement audio on unity3d , the instalation its fine , thats works and ambisonics bus is tested in the both platforms but the Wwisegvraudioroom script dont works when i put it in a gameobject. Then i put some other fx through the insert on Ambisonics auxiliar bus and this fx sounds.
Why this script dont works????

Thanks!

**Comment by jkammerl** [comment]
We would need a more detailed bug description with specific steps that describe exactly how to reproduce this bug in order to help you. Could you share more information?

**Comment by anokta** [comment]
Also, FYI, two things to check:
1. Make sure the _Room Effects Bus Name_ field on the WwiseGvrAudioRoom component has the correct name of your Audio Bus that the GVR Audio Room Effects plugin is attached.
2. Check if the listener and the game object that you would like to have room effects are inside the room you have created. You can modify the room's position/size using the Transform component to verify.

Let me know how it goes!
