### ISSUE TITLE
GVR DSP does not free up when bus falls silent

### ISSUE THREAD

**Issue by nlamartina** [googlevr/gvr-audio-wwise-sdk#4]
A new behavior has been introduced in 0.3 that causes the GVR plugin to not free up when its bus no longer has voices in it. This significantly impacts the designer's ability to manage CPU resources.

To replicate:
1. Start with a Wwise project with a GVR setup as detailed in the documentation.
2. Start the capturing with the Wwise Profiler.
3. Play a GVR voice. The GVR DSPs will allocate.
4. Stop the GVR voice.

RESULT: The GVR DSPs remain "stuck" and continue to churn CPU even though no voices are playing.
EXPECTED: The GVR DSPs free up after a couple of seconds and their CPU is freed up (as in previous versions).

![image](https://cloud.githubusercontent.com/assets/11888535/25108061/3366e26c-23a1-11e7-97fb-fa87c8ce5374.png)
Note in the image that there are no active events, but the DSPs are still processing.

**Comment by EgilSandfeld** [comment]
Can confirm I experience the same in my project.

I believe this also happened before version 0.3 though, as I saw CPU usage from the GVR Audio Renderer Plugin in Wwise Profiler in version 0.2, running about 3-6% when no audio was playing, after having played audio that was spatialized.

**Comment by anokta** [comment]
Thanks for reporting! This is a known issue for the renderer plugin, and we're currently working on it to resolve it ASAP. Sorry for the inconvenience.

**Comment by jkammerl** [comment]
This should be fixed in the v0.4.0 release. Thanks for your report.
